Repository hmcts/dtsse-dashboard-ingestion, pull requests merged in 2022-11, with the labels that each got.

#72 Find renovate.json in root directory
  src/main/query/github.dependabot.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-72

#73 Add sonar team and timestamp
  migrations/20221101093616-sonar-team-and-date.js
  migrations/sqls/20221101093616-sonar-team-and-date-down.sql
  migrations/sqls/20221101093616-sonar-team-and-date-up.sql
  src/main/query/sonar.project.ts
  src/main/sonar/team.test.ts
  src/main/sonar/team.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-73

#77 Add view for build step duration
  migrations/20221102082001-build-step-duration.js
  migrations/sqls/20221102082001-build-step-duration-down.sql
  migrations/sqls/20221102082001-build-step-duration-up.sql
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-77

#80 Refine gatling perf reports
  migrations/20221103140048-refine-gatling.js
  migrations/sqls/20221103140048-refine-gatling-down.sql
  migrations/sqls/20221103140048-refine-gatling-up.sql
  src/main/query/gatling.test.ts
  src/main/query/gatling.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-80

#82 compute step duration for each build step;
  migrations/20221104092157-materialize-step-time.js
  migrations/sqls/20221104092157-materialize-step-time-down.sql
  migrations/sqls/20221104092157-materialize-step-time-up.sql
  src/main/query/jenkins.metrics.test.ts
  src/main/query/jenkins.metrics.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-82

#83 Drop build step view
  migrations/20221104163747-drop-build-step-view.js
  migrations/sqls/20221104163747-drop-build-step-view-down.sql
  migrations/sqls/20221104163747-drop-build-step-view-up.sql
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-83

#93 Break out build step names into a table
  migrations/20221104203730-split-step-name.js
  migrations/sqls/20221104203730-split-step-name-down.sql
  migrations/sqls/20221104203730-split-step-name-up.sql
  src/main/query/jenkins.metrics.test.ts
  src/main/query/jenkins.metrics.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-93

#94 Add jira priotity, incident programme and project fields
  migrations/20221110140651-add-jira-fields.js
  migrations/sqls/20221110140651-add-jira-fields-down.sql
  migrations/sqls/20221110140651-add-jira-fields-up.sql
  src/main/query/jira.issue.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-94

#96 Add mapping between incident project and team
  migrations/20221111090049-jira-incident-team.js
  migrations/sqls/20221111090049-jira-incident-team-down.sql
  migrations/sqls/20221111090049-jira-incident-team-up.sql
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-96

#98 Map repositories to teams
  migrations/20221115064045-repository.js
  migrations/sqls/20221115064045-repository-down.sql
  migrations/sqls/20221115064045-repository-up.sql
  src/main/github/team.test.ts
  src/main/github/team.ts
  src/main/query/github.repository.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-98

#100 update ccd projects
  src/main/github/team.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-100

#103 quick fix for snow dep
  src/main/query/snow.incident.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-103

#104 Add snow secrets
  charts/dtsse-dashboard-ingestion/values.yaml
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-104

#106 Add time that snow incident was closed
  migrations/20221118071251-snow-closed-date.js
  migrations/sqls/20221118071251-snow-closed-date-down.sql
  migrations/sqls/20221118071251-snow-closed-date-up.sql
  src/main/query/snow.incident.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-106
