Repository hmcts/dtsse-dashboard-ingestion, pull requests merged in 2022-10, with the labels that each got.

#28 Add integration tests with testcontainers
  jest.integration.config.js
  package.json
  sonar-project.properties
  src/main/db/migrate.integration_test.ts
  src/main/db/migrate.test.ts
  yarn.lock
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-github-ingestion-pr-28

#30 Have all schemas in one repo
  README.md
  migrations/sqls/20220923135005-init-down.sql
  migrations/sqls/20220923135005-init-up.sql
  migrations/sqls/20220929091222-pull-request-down.sql
  migrations/sqls/20220929091222-pull-request-up.sql
  migrations/sqls/20221003143217-drop-tables-up.sql
  migrations/sqls/20221003162814-upsert-down.sql
  migrations/sqls/20221003162814-upsert-up.sql
  migrations/sqls/20221004090257-pr-state-down.sql
  migrations/sqls/20221004090257-pr-state-up.sql
  migrations/sqls/20221005085003-pr-timestamps-down.sql
  migrations/sqls/20221005085003-pr-timestamps-up.sql
  migrations/sqls/20221005101703-commit-hash-down.sql
  migrations/sqls/20221005101703-commit-hash-up.sql
  migrations/sqls/20221006081357-dependabot-down.sql
  migrations/sqls/20221006081357-dependabot-up.sql
  src/main/db/migrate.ts
  src/main/db/store.ts
  src/main/query/github.dependabot.ts
  src/main/query/github.pull-request.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-github-ingestion-pr-30

#31 move github files
  src/main/github/graphql.test.ts
  src/main/github/graphql.ts
  src/main/github/rest.test.ts
  src/main/github/rest.ts
  src/main/github/team.test.ts
  src/main/github/team.ts
  src/main/query/github.dependabot.ts
  src/main/query/github.pull-request.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-github-ingestion-pr-31

#32 Add JIRA ingestion
  charts/dtsse-dashboard-github-ingestion/Chart.yaml
  charts/dtsse-dashboard-github-ingestion/values.yaml
  migrations/20221006114527-init.js
  migrations/20221006145345-col-length.js
  migrations/sqls/20221006114527-init-down.sql
  migrations/sqls/20221006114527-init-up.sql
  migrations/sqls/20221006145345-col-length-down.sql
  migrations/sqls/20221006145345-col-length-up.sql
  package.json
  src/main/config.ts
  src/main/query/jira.issue.ts
  src/main/query/jira.project.ts
  yarn.lock
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-github-ingestion-pr-32

#35 Add jenkins pipeline metrics ingestion
  jest.integration.config.js
  migrations/20221007143236-jenkins-metrics.js
  migrations/sqls/20221007143236-jenkins-metrics-down.sql
  migrations/sqls/20221007143236-jenkins-metrics-up.sql
  package.json
  sonar-project.properties
  src/main/config.ts
  src/main/db/migrate.integration-test.ts
  src/main/db/migrate.integration_test.ts
  src/main/db/store.ts
  src/main/executor.ts
  src/main/jenkins/cosmos.ts
  src/main/query/jenkins.metrics.integration-test.ts
  src/main/query/jenkins.metrics.ts
  src/main/run.ts
  src/test_support/docker_helper.ts
  test_data/jenkins-metrics.json
  yarn.lock
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-35

#37 Pedantic renaming of files and folders
  jest.config.js
  jest.integration.config.js
  package.json
  sonar-project.properties
  src/main/db/migrate.integration-test.ts
  src/main/query/jenkins.metrics.integration-test.ts
  src/test/data/jenkins-metrics.json
  src/test/support/docker.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-37

#38 merge test suites
  jest.config.js
  jest.integration.config.js
  package.json
  sonar-project.properties
  src/main/db/migrate.test.ts
  src/main/query/jenkins.metrics.test.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-38

#39 exclude cosmos from coverage
  sonar-project.properties
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-39

#40 Fix fetching of last jenkins run timestamp
  src/main/query/jenkins.metrics.test.ts
  src/main/query/jenkins.metrics.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-40

#43 Ingest Gatling reports from cosmos
  migrations/20221017131105-gatling-reports.js
  migrations/sqls/20221017131105-gatling-reports-down.sql
  migrations/sqls/20221017131105-gatling-reports-up.sql
  src/main/jenkins/cosmos.ts
  src/main/query/gatling.test.ts
  src/main/query/gatling.ts
  src/test/data/gatling.json
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-43

#46 Add git commit hash
  migrations/20221021145102-jenkins-commit-hash.js
  migrations/sqls/20221021145102-jenkins-commit-hash-down.sql
  migrations/sqls/20221021145102-jenkins-commit-hash-up.sql
  src/main/query/jenkins.metrics.test.ts
  src/main/query/jenkins.metrics.ts
  src/test/data/jenkins-metrics.json
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-46

#52 Add build summary and terminal step views
  migrations/20221021085212-build-summaries.js
  migrations/sqls/20221021085212-build-summaries-down.sql
  migrations/sqls/20221021085212-build-summaries-up.sql
  src/main/query/jenkins.metrics.test.ts
  src/main/query/jenkins.metrics.ts
  src/test/data/jenkins-metrics.json
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-52

#51 Add timeout after 5 minutes
  package.json
  src/main/db/migrate.test.ts
  src/main/executor.ts
  src/main/query/gatling.test.ts
  src/main/query/jenkins.metrics.test.ts
  src/test/support/migrate.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-51

#53 add is_nightly column to builds
  migrations/20221024134011-add-is-nightly.js
  migrations/sqls/20221024134011-add-is-nightly-down.sql
  migrations/sqls/20221024134011-add-is-nightly-up.sql
  src/main/query/jenkins.metrics.test.ts
  src/main/query/jenkins.metrics.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-53

#54 fix failure reason selection
  migrations/20221024151432-fix-pipeline-failed.js
  migrations/sqls/20221024151432-fix-pipeline-failed-down.sql
  migrations/sqls/20221024151432-fix-pipeline-failed-up.sql
  src/main/query/jenkins.metrics.test.ts
  src/main/query/jenkins.metrics.ts
  src/test/data/jenkins-metrics.json
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-54

#60 Add jira resolution time, tweak query date ranges
  migrations/20221026085725-jira-resolution-date.js
  migrations/sqls/20221026085725-jira-resolution-date-down.sql
  migrations/sqls/20221026085725-jira-resolution-date-up.sql
  src/main/query/github.pull-request.ts
  src/main/query/jira.issue.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-60

#62 restructure team schema
  migrations/20221026123528-more-teams.js
  migrations/sqls/20221026123528-more-teams-down.sql
  migrations/sqls/20221026123528-more-teams-up.sql
  src/main/db/migrate.test.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-62

#63 Associate builds to teams
  migrations/20221026140856-associate-builds.js
  migrations/sqls/20221026140856-associate-builds-down.sql
  migrations/sqls/20221026140856-associate-builds-up.sql
  src/main/query/jenkins.metrics.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-63

#66 fix perf regression
  migrations/20221026154618-fix-perf-regression.js
  migrations/sqls/20221026154618-fix-perf-regression-down.sql
  migrations/sqls/20221026154618-fix-perf-regression-up.sql
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-66

#67 Add build duration to build summaries
  migrations/20221027094709-fix-perf-regression.js
  migrations/sqls/20221027094709-fix-perf-regression-down.sql
  migrations/sqls/20221027094709-fix-perf-regression-up.sql
  src/main/query/jenkins.metrics.test.ts
  src/main/query/jenkins.metrics.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-67
