Repository hmcts/dtsse-dashboard-ingestion, pull requests merged in 2023-06, with the labels that each got.

#327 Add more aliases based on namespace names
  migrations/20230607141621-add-more-aliases.js
  migrations/sqls/20230607141621-add-more-aliases-down.sql
  migrations/sqls/20230607141621-add-more-aliases-up.sql
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-327

#328 Add Helm chart base chart deprecation ingestion to postgresql
  migrations/20230609091902-helm-base-charts.js
  migrations/sqls/20230609091902-helm-base-charts-down.sql
  migrations/sqls/20230609091902-helm-base-charts-up.sql
  src/main/jenkins/cosmos.ts
  src/main/query/helm.base-charts.test.ts
  src/main/query/helm.base-charts.ts
  src/test/data/helm-base-charts.json
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-328

#334 Add HMC
  migrations/20230613095254-add-hmc.js
  migrations/sqls/20230613095254-add-hmc-down.sql
  migrations/sqls/20230613095254-add-hmc-up.sql
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-334

#335 remove team from helm chart table
  migrations/20230613102515-drop-team-from-helm-chart-table.js
  migrations/sqls/20230613102515-drop-team-from-helm-chart-table-down.sql
  migrations/sqls/20230613102515-drop-team-from-helm-chart-table-up.sql
  src/main/query/helm.base-charts.test.ts
  src/main/query/helm.base-charts.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-335
