Repository hmcts/dtsse-dashboard-ingestion, pull requests merged in 2023-07, with the labels that each got.

#355 Wait for all tasks to complete
  src/main/executor.ts
  yarn-audit-known-issues
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-355

#356 Use PlatOps auto merge renovate config
  .github/renovate.json
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-356

#369 fix allocation of idam java client and idam user disposer
  migrations/20230727131426-allocate-idam-projects.js
  migrations/sqls/20230727131426-allocate-idam-projects-up.sql
  src/main/query/jenkins.metrics.test.ts
  src/main/query/jenkins.metrics.ts
  src/test/data/jenkins-metrics.json
  yarn-audit-known-issues
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-369

#374 Avoid locking dashboard during jenkins processing
  migrations/20230728113233-jenkins-perf.js
  migrations/sqls/20230728113233-jenkins-perf-up.sql
  src/main/query/jenkins.metrics.test.ts
  src/main/query/jenkins.metrics.ts
Labels: ns:dtsse, prd:dtsse, rel:dtsse-dashboard-ingestion-pr-374
